version: "3.9"

services:
  neo4j:
    image: neo4j:5.26.9
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
    environment:
      NEO4J_AUTH: "neo4j/password"
      # JVM メモリ設定例
      # NEO4J_dbms_memory_heap_initial__size: "512m"
      # NEO4J_dbms_memory_heap_max__size: "1G"
    networks:
      - shared-network

networks:
  shared-network:
    name: ${PROJECT_NAME}-network
