version: "3"

services:
  mcp:
    restart: "no"
    tty: true
    build:
      context: ./
      dockerfile: docker/Dockerfile.mcp
    ports:
      - "127.0.0.1:9003:9003" # デバッグ用
    volumes:
      - ./projects/mcp:/project
    env_file:
      - ./env/.env.mcp
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8

  langflow:
    image: langflowai/langflow:1.6.4
    restart: unless-stopped
    # depends_on:
    #   postgres:
    #     condition: service_healthy
    ports:
      - "7860:7860" # http://localhost:7860
    env_file:
      - env/.env.langflow
    environment:
      LANGFLOW_SKIP_AUTH_AUTO_LOGIN: true
      LANGFLOW_AUTO_LOGIN: true
      LANGFLOW_AUTO_SAVING: true
      LANGFLOW_STORE_ENVIRONMENT_VARIABLES: true
      LANGFLOW_FALLBACK_TO_ENV_VAR: true
      LANGFLOW_LOAD_FLOWS_PATH: "/app/flows"
      LANGFLOW_DATABASE_URL: postgresql://langflow:secret@postgres:5432/langflow
    volumes:
      - langflow-data:/app/langflow
      - ./projects/langflow/imports:/app/flows:ro

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: langflow
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: langflow
    volumes:
      - langflow-postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U langflow -d langflow"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

volumes:
  langflow-data:
  langflow-postgres:
