services:
  # ---------------------------------
  # python
  # ---------------------------------
  python:
    restart: "no"
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:9000:9000" # デバッグ用
      - "0.0.0.0:8000:8000" # webサーバー
    volumes:
      - ./code:/project
      - huggingface_model:/root/.cache/huggingface/hub # ダウンロードしたモデルの保存
    networks:
      - shared-network
      - default

volumes:
  huggingface_model:

networks:
  shared-network:
    name: ${PROJECT_NAME}-network
