openapi: 3.0.0
info:
  title: Service API
  version: 0.0.1
  description: |
    swagger
components:
  securitySchemes:
    Authentication:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: access_token。<br>
        `Authorization Bearer eyj...` <br>
        ↑このようにヘッダにつけて飛ばしてください。
servers:
  - url: http://localhost:8000/
    description: api
paths:
  /hc/:
    get:
      tags:
        - HealthCheck
      summary: ALB Health-Check Endpoint.
      description: ALB Health-Check Endpoint.
      responses:
        "200":
          description: Health Check.
          content:
            application/json:
              example: "Healthy."
  # accounts
  /api/v1/accounts/login/:
    $ref: "endpoints/accounts_login.yml"
  /api/v1/accounts/login/confirm/:
    $ref: "endpoints/accounts_login_confirm.yml"
  /api/v1/accounts/me/:
    $ref: "endpoints/accounts_me.yml"
  /api/v1/accounts/refresh/:
    $ref: "endpoints/accounts_refresh.yml"

  # users
  /api/v1/users/:
    $ref: "endpoints/users.yml"
  /api/v1/users/{id}/:
    $ref: "endpoints/users_id.yml"
